# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  allow_concurrency: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: prospero_development
  username: prospero
  password: prospero

test:
  <<: *default
  database: prospero_test
  username: prospero
  password: prospero
